### ISSUE TITLE
Previous CPL season match pages do not load

### ISSUE THREAD

**Issue by BorislavHr** [janev94/CPL-web-issues#2]
Receive error 500 once I try to look at older season match pages.
![image](https://user-images.githubusercontent.com/91741504/222928347-4d951d7d-e9b5-4427-899c-6a1db2b66f34.png)

Navigation
View matches -> Regular season 
  -> drop-down menu Edition: 8 [go] 

e.g. [example](https://cplbw.com/cpl/view_matches/8/8/)

Error message: **Server Error (500)** 😆

**Comment by janev94** [comment]
@BorislavHr issue has now been resolved
